// <auto-generated />
using System;
using System.Collections.Generic;
using FamilyForPets.Volunteers.Infrastructure.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FamilyForPets.Volunteers.Infrastructure.Migrations
{
    [DbContext(typeof(VolunteerWriteDbContext))]
    [Migration("20250724185929_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FamilyForPets.Volunteers.Domain.Entities.Pet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContactPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("contact_phone_number");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("created_at");

                    b.Property<long?>("DateOfBirth")
                        .HasColumnType("bigint")
                        .HasColumnName("date_of_birth");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletion_date");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("pet_description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("PetHealthDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("pet_health_description");

                    b.Property<string>("PetPhotos")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("pet_photos_paths");

                    b.Property<int>("PetPosition")
                        .HasColumnType("integer")
                        .HasColumnName("pet_position");

                    b.Property<string>("PetVaccines")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("pet_vaccienes");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("volunteer_id")
                        .HasColumnType("uuid")
                        .HasColumnName("volunteer_id");

                    b.ComplexProperty<Dictionary<string, object>>("CastrationStatus", "FamilyForPets.Volunteers.Domain.Entities.Pet.CastrationStatus#CastrationStatus", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("castration_status_enum");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Color", "FamilyForPets.Volunteers.Domain.Entities.Pet.Color#PelageColor", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("PrimaryColor")
                                .HasColumnType("integer")
                                .HasColumnName("primary_color");

                            b1.Property<int?>("SecondaryColor")
                                .HasColumnType("integer")
                                .HasColumnName("secondary_color");

                            b1.Property<int?>("TertiaryColor")
                                .HasColumnType("integer")
                                .HasColumnName("tertiary_color");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Height", "FamilyForPets.Volunteers.Domain.Entities.Pet.Height#Length", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("Value")
                                .HasColumnType("double precision")
                                .HasColumnName("height");

                            b1.ComplexProperty<Dictionary<string, object>>("Type", "FamilyForPets.Volunteers.Domain.Entities.Pet.Height#Length.Type#LengthType", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("length_type_enum");
                                });
                        });

                    b.ComplexProperty<Dictionary<string, object>>("HelpStatus", "FamilyForPets.Volunteers.Domain.Entities.Pet.HelpStatus#HelpStatus", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("help_status_enum");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("PaymentDatails", "FamilyForPets.Volunteers.Domain.Entities.Pet.PaymentDatails#DetailsForPayment", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("CardNumber")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("card_number_for_payment");

                            b1.Property<string>("OtherDetails")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("other_payment_details");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("PetBreed", "FamilyForPets.Volunteers.Domain.Entities.Pet.PetBreed#PetBreedAndSpecies", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<Guid>("BreedId")
                                .HasColumnType("uuid")
                                .HasColumnName("breed_id");

                            b1.Property<Guid>("SpeciesId")
                                .HasColumnType("uuid")
                                .HasColumnName("species_id");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("PetCurrentAdress", "FamilyForPets.Volunteers.Domain.Entities.Pet.PetCurrentAdress#Adress", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("City")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("city");

                            b1.Property<string>("Country")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("country");

                            b1.Property<string>("HouseNumber")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("house_number");

                            b1.Property<string>("Street")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("street");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Weight", "FamilyForPets.Volunteers.Domain.Entities.Pet.Weight#Mass", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("Value")
                                .HasColumnType("double precision")
                                .HasColumnName("weight");

                            b1.ComplexProperty<Dictionary<string, object>>("Type", "FamilyForPets.Volunteers.Domain.Entities.Pet.Weight#Mass.Type#MassType", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("mass_type_enum");
                                });
                        });

                    b.HasKey("Id")
                        .HasName("pk_pets");

                    b.HasIndex("PetPosition")
                        .IsUnique()
                        .HasDatabaseName("ix_pets_pet_position");

                    b.HasIndex("volunteer_id")
                        .HasDatabaseName("ix_pets_volunteer_id");

                    b.ToTable("pets", null, t =>
                        {
                            t.HasCheckConstraint("CK_Height_BothOrNone", "(height IS NULL AND length_type_enum IS NULL) OR (height IS NOT NULL AND length_type_enum IS NOT NULL)");

                            t.HasCheckConstraint("CK_PaymentDetails_CardNumberRequiredIfOtherExists", "other_payment_details IS NULL OR card_number_for_payment IS NOT NULL");

                            t.HasCheckConstraint("CK_Weight_BothOrNone", "(weight IS NULL AND mass_type_enum IS NULL) OR (weight IS NOT NULL AND mass_type_enum IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("FamilyForPets.Volunteers.Domain.Entities.Volunteer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletion_date");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("volunteer_description");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<int>("ExperienceInYears")
                        .HasColumnType("integer")
                        .HasColumnName("experience_in_years");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("phone_number");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("VolunteerSocialNetworks")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("volunteer_social_networks");

                    b.ComplexProperty<Dictionary<string, object>>("DetailsForPayment", "FamilyForPets.Volunteers.Domain.Entities.Volunteer.DetailsForPayment#DetailsForPayment", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("CardNumber")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("card_number_for_payment");

                            b1.Property<string>("OtherDetails")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("other_payment_details");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("FullName", "FamilyForPets.Volunteers.Domain.Entities.Volunteer.FullName#FullName", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("AdditionalName")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("additional_name");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("first_name");

                            b1.Property<string>("Surname")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("last_name");
                        });

                    b.HasKey("Id")
                        .HasName("pk_volunteers");

                    b.ToTable("volunteers", (string)null);
                });

            modelBuilder.Entity("FamilyForPets.Volunteers.Domain.Entities.Pet", b =>
                {
                    b.HasOne("FamilyForPets.Volunteers.Domain.Entities.Volunteer", null)
                        .WithMany("AllPets")
                        .HasForeignKey("volunteer_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pets_volunteers_volunteer_id");
                });

            modelBuilder.Entity("FamilyForPets.Volunteers.Domain.Entities.Volunteer", b =>
                {
                    b.Navigation("AllPets");
                });
#pragma warning restore 612, 618
        }
    }
}
